name: Feature Request
description: Requesting a new feature or changes to an existing feature
title: '[FEATURE REQUEST] <feature name>'
labels: [enhancement]
body:
  - type: textarea
    id: currentproblem
    attributes:
      label: Problem
      description: Tell us about the problem.
    validations:
      required: true
  - type: textarea
    id: possiblesolution
    attributes:
      label: Possible Solution
      description: If you have an idea, please tell us what might solve the above problem.
    validations:
      required: true
  - type: textarea
    id: extrainformation
    attributes:
      label: Additional information
      description: Is there anything else we should know about this feature request?
    validations:
      required: false
