name: 'Stale'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latestlatest
    steps:
      - uses: actions/stale@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "Hello there,
          we have noticed that this PR has been inactive for a while now. If there are any changes which are suitable for our repository,
          we would love to have it. It would be great if you can continue with this PR, but if you can't, we might fork your changes and merge them ourselves.

          Since GitHub tracks contributions by commits, you'll still be credited.
          Let us know what you think about this. :slight_smile:


          Feel free to [join our Discord server](https://discord.gg/hScy8KWACQ) for support, hangouts, and more
          Thank you and have a nice day!"
        stale-pr-label: 'stale'
        days-before-pr-stale: 30
        days-before-pr-close: -1
