name: Check SVGs On PR
on: pull_request
jobs:
  check:
    name: Check the SVGs' quality
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install dependencies 
        run: python -m pip install --upgrade pip

      - name: Get Changed Files and generate files_added.json & files_modified.json
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the check_svg script
        run: >
          python ./.github/scripts/check_svgs_on_pr.py $HOME/files_added.json $HOME/files_modified.json

      - name: Upload the err messages
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: svg_err_messages
          path: ./svg_err_messages.txt

      - name: Save the pr num in an artifact
        shell: bash
        if: success()
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the pr num
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: pr_num
          path: ./pr_num.txt
