name: Check SVGs
on: pull_request
jobs:
  check:
    name: Check the SVGs' quality
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python v3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install dependencies 
        run: python -m pip install --upgrade pip
      - name: Run the check_svg script
        run: >
          python ./.github/scripts/check_svgs.py ./icomoon.json ./devicon.json ./icons
      - name: Comment on the PR about the result - Success
        if: success()
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        env:
          MESSAGE: |
            Hi!
            I'm Devicons' SVG-Checker Bot. All of your svgs seem fine.

            Thanks for your help,
      
            SVG-Checker Bot :smile:
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ env.MESSAGE }}

      - name: Comment on the PR about the result - Failed
        if: failure()
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        env:
          MESSAGE: |
            Hi!

            I'm Devicons' SVG-Checker Bot and it seems we've ran into a problem. I'm supposed to check your svgs but I couldn't do my task due to an issue.

            Here is what went wrong:
            ```
            {0}

            Please address these issues. When you update this PR, I will check your SVGs again.

            Thanks for your help,
      
            SVG-Checker Bot :smile:
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ format(env.MESSAGE, env.ERR_MSGS)}}
