name: On Develop PR Merge
on: 
  pull_request:
    types: [closed]
    branches: [develop]
jobs:
  save_pr_num_in_artifact:
    name: Preflight Label Issue In Develop
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python v3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/scripts/requirements.txt
          
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pr_num
          path: ./pr_num.txt
