name: Optimize icons
on:
  - pull_request
permissions: write-all

jobs:
  optimize:
    runs-on: ubuntu-latest
    name: Optimize icons with SVGO
    steps:
      - uses: actions/checkout@v3

      - uses: ericcornelissen/svgo-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          svgo-config: ./.github/scripts/svgo.config.js
          svgo-version: 3

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Icons optimized by SVGO
