name: Optimize the added/changed svgs
on:
  pull_request_target:
      types: [labeled]
jobs:
  peek:
    name: Optimize the added/changed svgs
    if: github.event.label.name == 'bot:optimize'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up gulp
        run: npm install

      - name: Run the optimize_svg script
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: npm run optimize-svg -- --iconsFolderPath="./icons" --prTitle="$PR_TITLE"

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Optimized the SVGs
