name: Test
on: pull_request
jobs: 
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Hi
        run: echo $EVENT_OBJ
        env:
          EVENT_OBJ: ${{ toJson(github.event.pull_request) }}